/** Helpers to turn a source file into a kb document: language detection, junk detection, fenced rendering. */

const BY_EXT: Record<string, string> = {
  ts: "typescript", mts: "typescript", cts: "typescript", tsx: "tsx",
  js: "javascript", mjs: "javascript", cjs: "javascript", jsx: "jsx",
  py: "python", kt: "kotlin", kts: "kotlin", java: "java", go: "go", cs: "csharp", rs: "rust", rb: "ruby", php: "php", scala: "scala",
  swift: "swift", dart: "dart", c: "c", h: "c", cpp: "cpp", hpp: "cpp", cc: "cpp", m: "objectivec",
  sql: "sql", sh: "bash", bash: "bash", zsh: "bash", ps1: "powershell", bat: "batch", cmd: "batch",
  tf: "hcl", tfvars: "hcl", hcl: "hcl", yaml: "yaml", yml: "yaml", toml: "toml", json: "json", jsonc: "json", ini: "ini", cfg: "ini", properties: "properties", env: "bash",
  proto: "protobuf", graphql: "graphql", gql: "graphql", prisma: "prisma", xml: "xml", csproj: "xml", gradle: "groovy", groovy: "groovy",
  html: "html", css: "css", scss: "scss", vue: "vue", svelte: "svelte", md: "markdown", mdx: "markdown", txt: "text", dockerfile: "dockerfile",
};

const BY_NAME: Record<string, string> = {
  dockerfile: "dockerfile", makefile: "makefile", jenkinsfile: "groovy", vagrantfile: "ruby", gemfile: "ruby", rakefile: "ruby", procfile: "text", ".env.example": "bash",
};

/** Fence language tag for a file path ("" when unknown). */
export function languageOf(filePath: string): string {
  const name = (filePath.split("/").pop() ?? "").toLowerCase();
  if (BY_NAME[name]) return BY_NAME[name] as string;
  if (name.startsWith("dockerfile.")) return "dockerfile";
  const dot = name.lastIndexOf(".");
  const ext = dot >= 0 ? name.slice(dot + 1) : "";
  return BY_EXT[ext] ?? "";
}

export interface CodeQualityLimits {
  maxLines: number;
  /** Average characters per line above which a file is treated as minified/generated. */
  maxAvgLineLength?: number;
}

/**
 * Reason not to index a file, or null when it looks like hand-written text. Cheap heuristics:
 * binary (NUL bytes), minified (very long lines), generated (marker in the header), too long.
 */
export function codeSkipReason(text: string, limits: CodeQualityLimits): string | null {
  if (!text.trim()) return "empty";
  if (text.slice(0, 8192).includes("\u0000")) return "binary";
  const head = text.slice(0, 2048);
  if (/@generated\b|auto-?generated|automatically generated|do not edit|generated by|<auto-generated/i.test(head)) return "generated file";
  const lines = text.split("\n");
  if (lines.length > limits.maxLines) return `too many lines (${lines.length})`;
  const avg = text.length / Math.max(1, lines.length);
  if (avg > (limits.maxAvgLineLength ?? 300)) return `minified or data file (avg line ${Math.round(avg)} chars)`;
  return null;
}

/** A fence longer than any backtick run inside the code, so the block cannot be closed early. */
export function fenceFor(code: string): string {
  const longest = Math.max(2, ...[...code.matchAll(/`+/g)].map((m) => m[0].length));
  return "`".repeat(longest + 1);
}

/** Render a source file as the body of a kb document: one fenced block, language-tagged. */
export function renderCodeBody(code: string, language: string): string {
  const fence = fenceFor(code);
  return `${fence}${language}\n${code.replace(/\r\n/g, "\n").replace(/\n+$/, "")}\n${fence}`;
}

/** Symbols declared in a piece of code (functions, classes, types...), across the common languages. */
const DECLARATION_RES: RegExp[] = [
  /^\s*(?:export\s+)?(?:default\s+)?(?:async\s+)?function\*?\s+([A-Za-z_$][\w$]*)/,
  /^\s*(?:export\s+)?(?:abstract\s+)?(?:class|interface|enum|type|namespace|module)\s+([A-Za-z_$][\w$]*)/,
  /^\s*(?:export\s+)?(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*(?::[^=]+)?=\s*(?:async\s*)?(?:\([^)]*\)|[A-Za-z_$][\w$]*)\s*(?::[^=]+)?=>/,
  /^\s*(?:export\s+)?(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:function|class|new\s|createSlice|defineComponent|styled|z\.|express|Fastify|Router)/,
  /^\s*(?:async\s+)?def\s+([A-Za-z_]\w*)/,
  /^\s*class\s+([A-Za-z_]\w*)/,
  /^\s*(?:public|private|protected|internal|open|abstract|final|static|override|suspend|inline|data|sealed|object|export|\s)*\s*(?:fun|func|class|interface|object|struct|enum|trait|impl|record|def)\s+(?:<[^>]+>\s*)?([A-Za-z_][\w]*)/,
  /^\s*(?:public|private|protected|internal|static|virtual|override|async|sealed|partial|readonly|\s)+[\w<>[\],.?]+\s+([A-Za-z_]\w*)\s*\(/,
  /^\s*func\s+(?:\([^)]*\)\s*)?([A-Za-z_]\w*)/,
  /^\s*(?:pub(?:\([^)]*\))?\s+)?(?:async\s+)?(?:fn|struct|enum|trait|mod|impl(?:<[^>]*>)?)\s+([A-Za-z_]\w*)/,
  /^\s*(?:CREATE|ALTER)\s+(?:OR\s+REPLACE\s+)?(?:TABLE|VIEW|FUNCTION|PROCEDURE|INDEX|TYPE|SCHEMA|TRIGGER|MATERIALIZED\s+VIEW)\s+(?:IF\s+NOT\s+EXISTS\s+)?([\w."]+)/i,
  /^\s*resource\s+"([^"]+)"\s+"([^"]+)"/,
  /^\s*(?:module|variable|output|data)\s+"([^"]+)"/,
  /^\s*(?:message|service|rpc|enum)\s+([A-Za-z_]\w*)/,
  /^\s*@(?:Get|Post|Put|Patch|Delete|RequestMapping|GetMapping|PostMapping|app\.(?:get|post|put|delete))\s*\(\s*["'`]([^"'`]+)/,
  /^\s*(?:router|app|server|fastify)\.(?:get|post|put|patch|delete|route)\s*\(\s*["'`]([^"'`]+)/,
];

export function declaredSymbols(code: string, max = 6): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  for (const line of code.split("\n")) {
    for (const re of DECLARATION_RES) {
      const m = re.exec(line);
      if (!m) continue;
      const sym = m.slice(1).filter(Boolean).join(".");
      if (sym && !seen.has(sym)) {
        seen.add(sym);
        out.push(sym);
      }
      break;
    }
    if (out.length >= max) break;
  }
  return out;
}

/** True when the line starts a top-level construct — the preferred place to cut a code chunk. */
export function isDeclarationStart(line: string): boolean {
  if (!line || /^\s/.test(line)) return false; // indented → inside something
  if (/^[})\]`'";,]/.test(line)) return false; // closing bracket / continuation
  if (/^(else|elif|catch|finally|case|default)\b/.test(line)) return false;
  if (/^(import|from|using|require|package|#include|#!)/.test(line)) return false;
  return /^[A-Za-z_@#$<-]/.test(line);
}
