/**
 * Cheap content-quality heuristics shared by the connectors: how much prose a markdown page carries,
 * whether it is a generated reference page, a boilerplate README, or a stub. They decide what is
 * *not* worth indexing — the knowledge base is meant to answer technical questions, and generated
 * API reference dumps, empty templates and scaffolding READMEs only dilute retrieval.
 */

export interface ProseStats {
  /** Words outside code fences, tables, headings and link-only lines. */
  proseWords: number;
  /** Non-empty table cells (a real reference table counts as content, an empty template does not). */
  tableCells: number;
  codeBlocks: number;
  headings: number;
  /** Lines that are only a link / image / nav arrow. */
  linkOnlyLines: number;
}

const LINK_ONLY = /^\s*(?:[-*]\s*)?(?:\[[^\]]*\]\([^)]*\)\s*|\[image:[^\]]*\]\s*|<https?:[^>]+>\s*|https?:\/\/\S+\s*)+$/i;

export function proseStats(md: string): ProseStats {
  const stats: ProseStats = { proseWords: 0, tableCells: 0, codeBlocks: 0, headings: 0, linkOnlyLines: 0 };
  let inFence = false;
  let fence = "";
  for (const raw of md.split("\n")) {
    const line = raw.trimEnd();
    const f = /^(\s*)(`{3,}|~{3,})/.exec(line);
    if (f) {
      const marker = f[2] as string;
      if (!inFence) {
        inFence = true;
        fence = marker;
        stats.codeBlocks++;
      } else if (line.trim().startsWith(fence)) inFence = false;
      continue;
    }
    if (inFence) continue;
    const t = line.trim();
    if (!t) continue;
    if (/^#{1,6}\s/.test(t)) {
      stats.headings++;
      continue;
    }
    if (t.startsWith("|")) {
      if (/^\|?\s*:?-{2,}/.test(t.replace(/^\|/, ""))) continue; // separator row
      for (const cell of t.split("|").slice(1, -1)) if (cell.trim()) stats.tableCells++;
      continue;
    }
    if (LINK_ONLY.test(t)) {
      stats.linkOnlyLines++;
      continue;
    }
    // Strip inline links/code/images, then count words of 2+ letters (Latin + accents).
    const text = t
      .replace(/!\[[^\]]*\]\([^)]*\)/g, " ")
      .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
      .replace(/`[^`]*`/g, " ")
      .replace(/<[^>]+>/g, " ");
    stats.proseWords += (text.match(/[\p{L}][\p{L}\p{M}'’-]+/gu) ?? []).length;
  }
  return stats;
}

/**
 * True when the page has nothing a reader could learn from: too few words of prose, no real table
 * content and no code. `minWords` is the prose threshold; tables and code blocks count as content.
 */
export function isStub(md: string, minWords: number): boolean {
  const s = proseStats(md);
  if (s.proseWords >= minWords) return false;
  if (s.codeBlocks > 0 && s.proseWords >= Math.floor(minWords / 3)) return false;
  return s.tableCells < 4;
}

/** Titles of pages generated from code by documentation tooling (Swagger/OpenAPI generators, Sphinx, JavaDoc...). */
const GENERATED_TITLE_RES: RegExp[] = [
  /^IO\.Swagger\./i,
  /^(?:[a-z_][\w]*\.){1,}[a-z_]\w*\s+(?:module|package|class|function)$/i, // sphinx: "pkg.sub.mod module"
  /^(?:[A-Z][\w]*\.){2,}[A-Z]\w*$/, // dotted CLR/Java type names: Foo.Bar.Baz
  /^(?:Model|Api|Class|Interface|Enum|Package|Namespace):\s/i,
  /^(?:Index of|Package Index|Module Index|Class Hierarchy)/i,
];

/** Body markers of generated documentation. */
const GENERATED_BODY_RES: RegExp[] = [
  /\[\[Back to (?:Model list|API list|README)\]\]/i,
  /\bThis file was (?:auto-?)?generated\b/i,
  /^Bases:\s+`/m, // sphinx autodoc
  /<!--\s*(?:auto-?generated|generated by)/i,
  /Generated by (?:Swagger Codegen|OpenAPI Generator|Sphinx|JavaDoc|TypeDoc|Doxygen)/i,
];

export function looksGenerated(title: string, md: string): boolean {
  if (GENERATED_TITLE_RES.some((re) => re.test(title.trim()))) return true;
  const head = md.slice(0, 3000);
  const tail = md.slice(-1500);
  return GENERATED_BODY_RES.some((re) => re.test(head) || re.test(tail));
}

/**
 * READMEs left over from a project generator (Create React App, Vite, Angular CLI, NestJS, Next.js...) are
 * identical across dozens of repositories and describe the tool, not the project.
 */
const BOILERPLATE_RES: RegExp[] = [
  /This project was bootstrapped with \[Create React App\]/i,
  /^#\s*React \+ TypeScript \+ Vite\b/m,
  /This template provides a minimal setup to get React working in Vite/i,
  /This project was generated (?:with|using) \[Angular CLI\]/i,
  /^#\s*Getting Started with Create React App/m,
  /This is a \[Next\.js\]\(https:\/\/nextjs\.org\) project bootstrapped with/i,
  /<p align="center">\s*<a href="http:\/\/nestjs\.com\/"/i,
  /## Description\s+\[Nest\]\(https:\/\/github\.com\/nestjs\/nest\) framework TypeScript starter repository/i,
  /This project was generated using \[Nx\]/i,
  /^#\s*Vue 3 \+ (?:TypeScript \+ )?Vite/m,
  /To make it easy for you to get started with GitLab, here's a list of recommended next steps/i, // GitLab's default README
  /^## Getting started\s+To make it easy for you to get started/im,
];

export function isBoilerplateReadme(md: string): boolean {
  const head = md.slice(0, 4000);
  return BOILERPLATE_RES.some((re) => re.test(head));
}

/** Normalised body hash key for cross-document duplicate detection (whitespace/case-insensitive). */
export function duplicateKey(md: string): string {
  return md
    .toLowerCase()
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .trim();
}
